name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Run tests with pytest
        env:
            aws_access_key_id_s3: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key_s3: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: python -m pytest tests/
